# Generated by Django 5.0.6 on 2024-06-13 19:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_about_description_alter_services_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
